#!/usr/bin/env node
/**
 * Generate src/erc8004/registry.generated.ts from an address
 * registry (addresses.json, system `standards-erc8004`).
 *
 *   node scripts/gen-erc8004.mjs <path/to/addresses.json>
 *   ADDRESSES_JSON=<path/to/addresses.json> node scripts/gen-erc8004.mjs
 *   node scripts/gen-erc8004.mjs <path> --check   # exit 1 if the committed file is stale
 *
 * No dependencies. The generated file is committed; never hand-edit it.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SYSTEM = 'standards-erc8004';
const args = process.argv.slice(2);
const check = args.includes('--check');
const src = args.find((a) => !a.startsWith('--')) ?? process.env.ADDRESSES_JSON;
if (!src) {
  console.error('usage: gen-erc8004.mjs <addresses.json> [--check]  (or set ADDRESSES_JSON)');
  process.exit(2);
}

const reg = JSON.parse(readFileSync(src, 'utf8'));
const system = reg.systems?.[SYSTEM];
if (!system) throw new Error(`system ${SYSTEM} not found in ${src}`);

const ROLE = [
  [/identity registry/i, 'identity'],
  [/reputation registry/i, 'reputation'],
  [/validation registry/i, 'validation'],
];
const roleOf = (name) => {
  const hit = ROLE.find(([re]) => re.test(name));
  if (!hit) throw new Error(`unrecognised ERC-8004 contract name: ${name}`);
  return hit[1];
};

/** chainId -> { name, status, identity?, reputation?, validation? } */
const byChain = new Map();
for (const c of system.contracts) {
  if (!/^0x[0-9a-fA-F]{40}$/.test(c.address)) throw new Error(`bad address ${c.address}`);
  const role = roleOf(c.name);
  const row = byChain.get(c.chain) ?? { name: reg.chains?.[String(c.chain)]?.name ?? String(c.chain), status: c.status };
  if (row[role]) throw new Error(`two ${role} registries on chain ${c.chain}`);
  if (row.status !== c.status) throw new Error(`mixed status on chain ${c.chain}`);
  row[role] = c.address;
  byChain.set(c.chain, row);
}

/* The canonical set: the addresses every live (non-devnet) chain shares. */
const live = [...byChain.entries()].filter(([, r]) => r.status === 'live');
if (live.length === 0) throw new Error('no live ERC-8004 deployment in the registry');
const canonical = {};
for (const role of ['identity', 'reputation', 'validation']) {
  const set = new Set(live.map(([, r]) => r[role]));
  if (set.size !== 1) {
    if ([...set].some(Boolean)) throw new Error(`${role} differs across live chains`);
    continue; // absent on every live chain
  }
  const [addr] = set;
  if (addr) canonical[role] = addr;
}

const q = (s) => `'${s}'`;
const entry = (r) => {
  const parts = [`name: ${q(r.name)}`, `status: ${q(r.status)}`];
  for (const role of ['identity', 'reputation', 'validation']) if (r[role]) parts.push(`${role}: ${q(r[role])}`);
  return `{ ${parts.join(', ')} }`;
};
const chains = [...byChain.entries()].sort(([a], [b]) => a - b);

const out = `/* GENERATED FILE, DO NOT EDIT BY HAND.
 *
 * Generated by scripts/gen-erc8004.mjs from an address registry
 * (addresses.json), system \`${SYSTEM}\`, registry version ${reg.version}, updated ${reg.updated}.
 * To change an address, change the registry and re-run the generator.
 *
 * A registry the source does not record on a chain is absent here, never guessed.
 */

/** Registry roles recorded per chain. A missing key means no deployment is recorded. */
export interface Erc8004ChainDeployment {
  readonly name: string;
  readonly status: 'live' | 'devnet-only' | string;
  readonly identity?: string;
  readonly reputation?: string;
  readonly validation?: string;
}

/** Every ERC-8004 deployment the registry records, by chain id. */
export const ERC8004_DEPLOYMENTS: Readonly<Record<number, Erc8004ChainDeployment>> = Object.freeze({
${chains.map(([id, r]) => `  ${id}: Object.freeze(${entry(r)}),`).join('\n')}
});

/** The canonical addresses, shared by every live chain above (${live.map(([id, r]) => `${r.name} ${id}`).join(', ')}). */
export const ERC8004_CANONICAL: Readonly<{ identity?: string; reputation?: string; validation?: string }> = Object.freeze({
${Object.entries(canonical).map(([k, v]) => `  ${k}: ${q(v)},`).join('\n')}
});
`;

const here = dirname(fileURLToPath(import.meta.url));
const dest = resolve(here, '../src/erc8004/registry.generated.ts');
if (check) {
  let cur = '';
  try { cur = readFileSync(dest, 'utf8'); } catch {}
  if (cur !== out) { console.error(`${dest} is stale; re-run the generator`); process.exit(1); }
  console.log('registry.generated.ts is up to date');
} else {
  writeFileSync(dest, out);
  console.log(`wrote src/erc8004/registry.generated.ts (${chains.length} chains, canonical: ${Object.keys(canonical).join(', ')})`);
}
